server:
  port: 2080

host:
  apiKey: ${api_key}

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      authentication-database: admin
      database: files
      port: '27017'
      host: localhost

