server:
  port: 9040
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/invoice_db
    username: postgres
    password: postgres            
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      connectionTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true 

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    file:
      name: file_exchange
  queue:
    management:
      invoice:
        name: management_invoice_queue
    invoice:
      file:
        name: invoice_file_queue
  binding:
    invoice:
      file:
        routing:
          key: invoice_file_routing_key


