server:
  port: 9005
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: maintenance_db

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
