spring:
  datasource:
    url: jdbc:mysql://localhost:3306/production_db
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      connectionTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true 

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
